name = mm3col
description = A 3 column layout with for MMORPG
preview = preview.png
template = mm3col-layout

; Regions
regions[header]         = Header
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = ../css/mmorpg.styles.css
