<?php
/**
 * @file
 * Provide custom shortcodes for mmorpg.com
 */

/**
 * Implementation of hook_js_alter().
 * Replace the shortcode_wysiwwyg.js with our custom version
 */
function mmorpg_wysiwyg_plugin_js_alter(&$javascript) {
  $path = drupal_get_path('module', 'mmorpg_wysiwyg_plugin') . '/plugins/shortcode_wysiwyg/shortcode_wysiwyg.js';
  if( isset($javascript[$path]) ) {
    $javascript[$path]['data'] = drupal_get_path('module', 'mmorpg_wysiwyg_plugin') . '/shortcode_wysiwyg.js';
  }
}

/**
 * Implementation of hook_shortcode_info().
 */
function mmorpg_wysiwyg_plugin_shortcode_info() {
  $shortcodes = array();

  $shortcodes['poll'] = array(
    'title' => t('Add poll'),
    'description' => t('Creates a poll.'),
    'process callback' => 'mmorpg_wysiwyg_plugin_sortcode_poll',
    'tips callback' => 'mmorpg_wysiwyg_plugin_shortcode_poll_tips',
    'default settings' => array(),
    'attributes callback' => 'mmorpg_wysiwyg_plugin_shortcode_poll_attributes',
  );

  $shortcodes['related-content'] = array(
    'title' => t('Related Content'),
    'description' => t('Add related content.'),
    'process callback' => 'mmorpg_wysiwyg_plugin_sortcode_related_content',
    'tips callback' => 'mmorpg_wysiwyg_plugin_shortcode_related_content_tips',
    'default settings' => array(),
    'attributes callback' => 'mmorpg_wysiwyg_plugin_shortcode_related_content_attributes',
  );

  $shortcodes['play-now'] = array(
    'title' => t('Play Now'),
    'description' => t('Add play now.'),
    'process callback' => 'mmorpg_wysiwyg_plugin_sortcode_play_now',
    'tips callback' => 'mmorpg_wysiwyg_plugin_shortcode_play_now_tips',
    'default settings' => array(),
    'attributes callback' => 'mmorpg_wysiwyg_plugin_shortcode_play_now_attributes',
  );

  return $shortcodes;
}

/**
 * Implementation of hook_theme().
 */
function mmorpg_wysiwyg_plugin_theme() {
  return array(
    'poll' => array(
      'variables' => array( 'text' => '', 'class' => ''),
    ),
    'related_content' => array(
      'variables' => array( 'text' => '', 'class' => ''),
    ),
  );
}

/*============================================================================================*/
/* Embed Poll
/*============================================================================================*/
function mmorpg_wysiwyg_plugin_sortcode_poll($attrs, $text) {
  extract(shortcode_attrs(array(
    'poll_id' => '',
    'class' => '',
  ), $attrs));

  if(isset($attrs['poll_id'])) {
    $poll_id = $attrs['poll_id'];
    $pollim = pollim_load($poll_id);
    if(is_object($pollim)) {
      $poll = pollim_page_view($pollim);
      return render($poll);
    }
  }
}

function mmorpg_wysiwyg_plugin_shortcode_poll_tips() {
  $output = '<strong>[poll poll_id="POLL ID HERE"][/poll]</strong>';

  return $output;
}

function mmorpg_wysiwyg_plugin_shortcode_poll_attributes($form, $form_state) {
  $form['poll_id'] = array(
    '#type' => 'textfield',
    '#title' => t('Poll ID'),
    '#size' => 60,
    '#maxlength' => 60,
    '#states' => array(
      'visible' => array(
        ':input[name="shortcode"]' => array('value' => 'poll'),
      ),
    ),
  );
  return $form;
}

/*============================================================================================*/
/* Embed Related Content
/*============================================================================================*/
function mmorpg_wysiwyg_plugin_sortcode_related_content($attrs, $text) {
  return '[related-content][/related-content]';
}

function mmorpg_wysiwyg_plugin_shortcode_related_content_tips() {
  $output = '<strong>[related-content][/related-content]</strong>';

  return $output;
}

function mmorpg_wysiwyg_plugin_shortcode_related_content_attributes($form, $form_state) {
  $form = array();
  return $form;
}

/*============================================================================================*/
/* Embed Play Now
/*============================================================================================*/
function mmorpg_wysiwyg_plugin_sortcode_play_now($attrs, $text) {
  extract(shortcode_attrs(array(
    'playnow_id' => '',
    'class' => '',
  ), $attrs));

  if(!empty($attrs['playnow_id']) && is_numeric($attrs['playnow_id'])) {
    $content = '';
    $nid = $attrs['playnow_id'];

    $query_signup_now = "SELECT field_target_url_title, field_target_url_clickmeter_link from {field_data_field_target_url} WHERE entity_id = ". $nid;
    $result_signup_now = db_query($query_signup_now);

    $query_game_content = "SELECT field_game_contents_target_id from {field_data_field_game_contents} WHERE entity_id = " . $nid;
    $result_game_content = db_query($query_game_content);

    foreach ($result_game_content as $row){
      if (!empty($row->field_game_contents_target_id)) {
        $game_content_id = $row->field_game_contents_target_id;
      }
    }

    if (!empty($game_content_id)) {
      $query_company_url = "SELECT field_link_url FROM {field_data_field_link} WHERE entity_id = " . $game_content_id;
      $result_company_url = db_query($query_company_url);

      foreach ($result_company_url as $row) {
        if (!empty($row->field_link_url)) {
          $company_url = $row->field_link_url;
        }
      }
    }

    foreach ($result_signup_now as $row){
      if (!empty($row->field_target_url_clickmeter_link)) {
        $content .= "<a href=". $row->field_target_url_clickmeter_link .">". $row->field_target_url_title . "</a></li></ul>";
      }
      else if (!empty($company_url)) {
        $content .= "<a href=". $company_url .">". $row->field_target_url_title . "</a></li></ul>";
      }
    }

    return $content;
  }
  else {
    return '';
  }
}

function mmorpg_wysiwyg_plugin_shortcode_play_now_tips() {
  $output = '<strong>[shortcode planow_id = "SIGNUP NOW NODE ID"][/shortcode]</strong>';

  return $output;
}

function mmorpg_wysiwyg_plugin_shortcode_play_now_attributes($form, $form_state) {
  $form['playnow_id'] = array(
    '#type' => 'textfield',
    '#title' => t('Node ID'),
    '#size' => 60,
    '#maxlength' => 60,
    '#states' => array(
      'visible' => array(
        ':input[name="shortcode"]' => array('value' => 'play-now'),
      ),
    ),
  );
  return $form;
}