<?php
/**
 * @file
 * Provide custom shortcodes for mmorpg.com
 */

/**
 * Implementation of hook_js_alter().
 * Replace the shortcode_wysiwwyg.js with our custom version
 */
function mmorpg_wysiwyg_plugin_js_alter(&$javascript) {
  $path = drupal_get_path('module', 'mmorpg_wysiwyg_plugin') . '/plugins/shortcode_wysiwyg/shortcode_wysiwyg.js';
  if( isset($javascript[$path]) ) {
    $javascript[$path]['data'] = drupal_get_path('module', 'mmorpg_wysiwyg_plugin') . '/shortcode_wysiwyg.js';
  }
}

/**
 * Implementation of hook_shortcode_info().
 */
function mmorpg_wysiwyg_plugin_shortcode_info() {
  $shortcodes = array();

  $shortcodes['poll'] = array(
    'title' => t('Add poll'),
    'description' => t('Creates a poll.'),
    'process callback' => 'mmorpg_wysiwyg_plugin_sortcode_poll',
    'tips callback' => 'mmorpg_wysiwyg_plugin_shortcode_poll_tips',
    'default settings' => array(),
    'attributes callback' => 'mmorpg_wysiwyg_plugin_shortcode_poll_attributes',
  );

  $shortcodes['related-content'] = array(
    'title' => t('Related Content'),
    'description' => t('Add related content.'),
    'process callback' => 'mmorpg_wysiwyg_plugin_sortcode_related_content',
    'tips callback' => 'mmorpg_wysiwyg_plugin_shortcode_related_content_tips',
    'default settings' => array(),
    'attributes callback' => 'mmorpg_wysiwyg_plugin_shortcode_related_content_attributes',
  );

  $shortcodes['play-now'] = array(
    'title' => t('Play Now'),
    'description' => t('Add play now.'),
    'process callback' => 'mmorpg_wysiwyg_plugin_sortcode_play_now',
    'tips callback' => 'mmorpg_wysiwyg_plugin_shortcode_play_now_tips',
    'default settings' => array(),
    'attributes callback' => 'mmorpg_wysiwyg_plugin_shortcode_play_now_attributes',
  );

  return $shortcodes;
}

/**
 * Implementation of hook_theme().
 */
function mmorpg_wysiwyg_plugin_theme() {
  return array(
    'poll' => array(
      'variables' => array( 'text' => '', 'class' => ''),
    ),
    'related_content' => array(
      'variables' => array( 'text' => '', 'class' => ''),
    ),
  );
}

/*============================================================================================*/
/* Embed Poll
/*============================================================================================*/
function mmorpg_wysiwyg_plugin_sortcode_poll($attrs, $text) {
  extract(shortcode_attrs(array(
    'poll_id' => '',
    'class' => '',
  ), $attrs));

  if(isset($attrs['poll_id'])) {
    $poll_id = $attrs['poll_id'];
    $pollim = pollim_load($poll_id);
    if(is_object($pollim)) {
      $poll = pollim_page_view($pollim);
      return render($poll);
    }
  }
}

function mmorpg_wysiwyg_plugin_shortcode_poll_tips() {
  $output = '<strong>[poll poll_id="POLL ID HERE"][/poll]</strong>';

  return $output;
}

function mmorpg_wysiwyg_plugin_shortcode_poll_attributes($form, $form_state) {
  $form['poll_id'] = array(
    '#type' => 'textfield',
    '#title' => t('Poll ID'),
    '#size' => 60,
    '#maxlength' => 60,
    '#states' => array(
      'visible' => array(
        ':input[name="shortcode"]' => array('value' => 'poll'),
      ),
    ),
  );
  return $form;
}

/*============================================================================================*/
/* Embed Related Content
/*============================================================================================*/
function mmorpg_wysiwyg_plugin_sortcode_related_content($attrs, $text) {
  extract(shortcode_attrs(array(
    'node_id' => '',
    'class' => '',
  ), $attrs));

  if(!empty($attrs['node_id'])) {
    $nid = trim($attrs['node_id']);
    $node = node_load($nid);
    if (empty($node) || !$node->status || !node_access('view', $node)) {
      return '';
    }
    $node->shortcode_embedded = TRUE;
  }
  else {
    return '';
  }

  $params = new stdClass();
  $params->view_mode = 'teaser';
  $content = node_view($node, $params->view_mode);

  return render($content);
}

function mmorpg_wysiwyg_plugin_shortcode_related_content_tips() {
  $output = '<strong>[related-content node_id="NODE ID HERE"][/related-content]</strong>';

  return $output;
}

function mmorpg_wysiwyg_plugin_shortcode_related_content_attributes($form, $form_state) {
  $form['node_id'] = array(
    '#type' => 'textfield',
    '#title' => t('Node ID'),
    '#size' => 60,
    '#maxlength' => 60,
    '#states' => array(
      'visible' => array(
        ':input[name="shortcode"]' => array('value' => 'related-content'),
      ),
    ),
  );
  return $form;
}

/*============================================================================================*/
/* Embed Related Content
/*============================================================================================*/
function mmorpg_wysiwyg_plugin_sortcode_play_now($attrs, $text) {
  extract(shortcode_attrs(array(
    'playnow_id' => '',
    'class' => '',
  ), $attrs));

  if(!empty($attrs['playnow_id'])) {
    $nid = trim($attrs['playnow_id']);
    $node = node_load($nid);
    if (empty($node) || !$node->status || !node_access('view', $node) || $node->type != 'play_now_slides') {
      return '';
    }
    $node->shortcode_embedded = TRUE;
  }
  else {
    return '';
  }

  $params = new stdClass();
  $params->view_mode = 'teaser';
  $content = node_view($node, $params->view_mode);

  return render($content);
}

function mmorpg_wysiwyg_plugin_shortcode_play_now_tips() {
  $output = '<strong>[play-now playnow_id="NODE ID HERE"][/play-now]</strong>';

  return $output;
}

function mmorpg_wysiwyg_plugin_shortcode_play_now_attributes($form, $form_state) {
  $form['playnow_id'] = array(
    '#type' => 'textfield',
    '#title' => t('Node ID'),
    '#size' => 60,
    '#maxlength' => 60,
    '#states' => array(
      'visible' => array(
        ':input[name="shortcode"]' => array('value' => 'play-now'),
      ),
    ),
  );
  return $form;
}