<?php
/**
 * @file
 * Code for the MMORPG Site Configs feature.
 */

include_once 'mmorpg_site.features.inc';

/**
 * Implements hook_menu().
 */
function mmorpg_site_menu() {
  $items['admin/mmorpg/reports'] = array(
    'title' => 'Reports',
    'description' => 'Access various advt. reports',
    'access callback' => TRUE,
    'type' => MENU_LOCAL_TASK,
  );
  $items['admin/mmorpg/reports/blank'] = array(
    'title' => 'Reports',
    'access callback' => TRUE,
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  return $items;
}