<?php
/**
 * @file
 * Code for the Sweepstakes feature.
 */

include_once 'sweepstakes.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function sweepstakes_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && !empty($plugin)) {
    return "plugins/$plugin";
  }
}

/**
 * Implements hook_block_info().
 */
function sweepstakes_block_info() {
  $blocks['sweepstakes_entry_block'] = array(
    'info' => t('Sweepstakes Entry Block'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['sweepstakes_title_rss_block'] = array(
    'info' => t('Sweepstakes Title & RSS Block'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function sweepstakes_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'sweepstakes_entry_block':
      $block['content'] = drupal_get_form('sweepstakes_entry_form');
      break;
    case 'sweepstakes_title_rss_block':
      $block['content'] = _sweepstakes_show_title_rss();
      break;
  }
  return $block;
}

function sweepstakes_entry_form() {
  return array(
    'sid' => array(
      '#type' => 'hidden',
      '#value' => arg(1),
    ),
    'share' => array(
      '#type' => 'checkbox',
      '#default_value' => TRUE,
      '#title' => t('I have read, understand and agree to the above contest rules'),
    ),
    'signup' => array(
      '#type' => 'checkbox',
      '#default_value' => TRUE,
      '#title' => t('Check here if you would like us to e-mail you about contests like this in the future'),
    ),
    'submit' => array(
      '#type' => 'submit',
      '#value' => t('Enter Contest'),
      '#attributes' => array(
        'class' => array('btn large green'),
      ),
    ),
  );
}

function sweepstakes_entry_form_submit($form, &$form_state) {
  global $user;
  if (_sweepstakes_check_unique_entry($form_state['values']['sid'], $user->uid)) {
    _sweepstakes_add_entry($form_state['values']['sid'], $user->uid, NULL, NULL, 'user initiated');
  }
}

function _sweepstakes_check_unique_entry($nid, $uid) {
  $entries = db_select('sweepstakes_entries')
    ->fields(NULL, array('seid'))
    ->condition('nid', $nid)
    ->condition('uid', $uid)
    ->execute()
    ->rowCount();

  if ($entries > 0) {
    drupal_set_message(t('You are already enrolled in this sweepstakes'), 'error');
    return FALSE;
  }
  return TRUE;
}

function _sweepstakes_add_entry($nid, $uid = NULL, $ip_address = NULL, $timestamp = NULL, $source = NULL) {
  if (is_null($uid)) {
    global $user;
    $uid = $user->uid;
  }

  if (is_null($ip_address)) {
    $ip_address = ip2long(ip_address());
  }

  if (is_null($timestamp)) {
    $timestamp = time();
  }

  db_insert('sweepstakes_entries')
    ->fields(array(
      'seid' => 0,
      'nid' => $nid,
      'uid' => $uid,
      'ip_address' => $ip_address,
      'timestamp' => $timestamp,
      'source' => $source,
    ))
    ->execute();

  drupal_set_message(t('You have successfully entered the sweepstakes'));
}

function _sweepstakes_show_title_rss() {
  return "
  <div class='pane-mmorpg-game-game-rss-link-block'>
  <h2 class='title_crumbs'>
      Sweepstakes
  </h2>"
  . l('RSS', 'sweepstakes/rss.xml') .
  "</div>";
}