<?php
/**
 * @file
 * Module for continuous integration.
 */

/**
 * Helper function for reverting feature.
 */
function mmorpg_util_features_revert($modules) {
  module_load_include('inc', 'features', 'features.export');
  features_include();
  foreach ($modules as $module) {
    $components = array();
    if (($feature = feature_load($module, TRUE)) && module_exists($module)) {
      // Forcefully revert all components of a feature.
      foreach (array_keys($feature->info['features']) as $component) {
        if (features_hook($component, 'features_revert')) {
          $components[] = $component;
        }
      }
    }
    foreach ($components as $component) {
      features_revert(array($module => array($component)));
    }
  }
}


/**
 * Simulation of `drush fra -y`
 */
function mmorpg_drush_fra() {
  module_load_include('drush.inc', 'features', 'features');
  drush_features_revert_all();
  return 1;
}

/**
 * Simulation of `drush cc all`
 */
function mmorpg_drush_cc_all() {
  cache_clear_all();
  return 1;
}

/**
 * This is a convenient deploy shortcut.
 */
function mmorpg_deploy() {
  mmorpg_drush_fra() and mmorpg_drush_cc_all();
}
