<?php
/**
 * @file
 * Code for the giveaway feature.
 */

include_once 'giveaway.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function giveaway_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && !empty($plugin)) {
    return "plugins/$plugin";
  }
}

/**
 * Implements hook_feeds_processor_targets_alter().
 */
function giveaway_feeds_processor_targets_alter(&$targets, $entity_type, $bundle_name) {
  if ($entity_type == 'data_giveaway_keys') {
    $targets['gid']['callback'] = 'giveaway_gid_set_target';
  }
}

function giveaway_gid_set_target($source, $entity, $target, $value, $mapping) {
  $entity->{$mapping['target']} = $entity->feeds_item->{$mapping['source']};
}

/**
 * Implements hook_block_info().
 */
function giveaway_block_info() {
  $blocks['giveaway_claim_block'] = array(
    'info' => t('Giveaway Claim Block'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['giveaway_keys_left_block'] = array(
    'info' => t('Giveaway Keys Left Block'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function giveaway_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'claim_block':
      $block['content'] = drupal_get_form('_giveaway_show_claim_button');
      break;
    case 'giveaway_keys_left_block':
      $block['content'] = _giveaway_show_keys_left();
      break;
  }
  return $block;
}

function _giveaway_show_claim_button() {
  return array(
    'gid' => array(
      '#type' => 'hidden',
      '#value' => @end(arg()),
    ),
    'claim_button' => array(
      '#type' => 'submit',
      '#value' => t('Click Here To Get Your Beta Key Information!'),
      '#attributes' => array(
        'class' => array('btn large full cta'),
      )
    ),
  );
}

function _giveaway_show_keys_left() {
  $count = db_select('giveaway_keys')
    ->fields(NULL, array('gkid'))
    ->condition('available', 1)
    ->condition('gid', @end(arg()))
    ->execute()
    ->rowCount();
  return "<div class='remainingkeys'>" . t('@count Keys Left', array('@count' => number_format($count))) . "</div>";
}
