#!/bin/sh
#Use this script for executing operations on the dev instance after 
#the code is deployed via projspace. This does not combine with
#git's deployhook. This only gets executed while you choose a version
#via projspace's UI.

#Put all of your actions before #EOF.

cd /home/mmorpg/www/dev/docroot
drush updb -y && drush rr && drush fra -y && drush cc all
drush aa --html --bootstrap --detail --skip=insights > sites/default/files/report.html

#EOF

